name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build, analyse and run tests
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.1.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build and Test
        run: |
          xcodebuild \
            -project ActivityList/ActivityList.xcodeproj \
            -scheme ActivityList \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            clean \
            build \
            test \
            | xcpretty && exit ${PIPESTATUS[0]}

          # xcodebuild clean build test -project ActivityList/ActivityList.xcodeproj -scheme "ActivityList" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=iOS Simulator,name=iPhone 15" ONLY_ACTIVE_ARCH=YES | xcpretty && exit ${PIPESTATUS[0]}
